import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import { ContextProvider } from "@/contexts/ContextsProvider";

import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "San Francisco City Academy",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <link
        rel="icon"
        href="https://i.ibb.co/cFYDXTW/Screenshot-54-removebg-preview.png"
      />

      <body className={inter.className} style={{backgroundColor:"#142738"}}>
        <SessionProvider session={session}>
          <ContextProvider>
            <Navbar />

            {children}

            <Footer />
          </ContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
